# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
import tkinter as tk
from tkinter import Tk, ttk, Canvas, Entry, Button, PhotoImage

from PIL import Image, ImageTk

# from ttkbootstrap.tableview import Tableview

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets/frame0")


# print(type(OUTPUT_PATH))
# print(type(ASSETS_PATH
def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("864x605")
window.configure(bg="wheat")
window.title("shusha")
# window.iconbitmap("shusha.ico")
im = Image.open("shusha.ico")
photo = ImageTk.PhotoImage(im)
window.wm_iconphoto(True, photo)
window.resizable(False, False)


canvas = Canvas(
    window,
    bg="gray22",
    height=605,
    width=864,
    bd=0,
    highlightthickness=0,
    relief="ridge",
)
canvas.place(x=0, y=0)

# top panel
canvas.create_rectangle(0.0, 541.0, 864.0, 605.0, fill="#2A2E31", outline="")

button_image_add = PhotoImage(file=relative_to_assets("icons8-add-64.png"))
button__add = Button(
    image=button_image_add,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("add downloads"),
    relief="flat",
)
button__add.place(x=10.0, y=7.0, width=50.0, height=50.0)


button_image_play = PhotoImage(file=relative_to_assets("icons8-circled-play-64.png"))
button_play = Button(
    image=button_image_play,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("strat download"),
    relief="flat",
)
button_play.place(x=65.0, y=7.0, width=50.0, height=50.0)

button_image_pause = PhotoImage(file=relative_to_assets("icons8-pause-button-64.png"))
button_pause = Button(
    image=button_image_pause,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("pause download"),
    relief="flat",
)
button_pause.place(x=120.0, y=7.0, width=50.0, height=50.0)

button_image_up = PhotoImage(file=relative_to_assets("icons8-arrow-64.png"))
button_up = Button(
    image=button_image_up,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Move up"),
    relief="flat",
)
button_up.place(x=175.0, y=7.0, width=50.0, height=50.0)

button_image_down = PhotoImage(file=relative_to_assets("icons8-scroll-down-64.png"))
button_down = Button(
    image=button_image_down,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Move down"),
    relief="flat",
)
button_down.place(x=230.0, y=7.0, width=50.0, height=50.0)

button_image_log = PhotoImage(file=relative_to_assets("icons8-log-64.png"))
button_log = Button(
    image=button_image_log,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("open logs"),
    relief="flat",
)
button_log.place(x=749.0, y=7.0, width=50.0, height=50.0)

button_image_sett = PhotoImage(file=relative_to_assets("icons8-slider_2-64.png"))
button_sett = Button(
    image=button_image_sett,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("open settings"),
    relief="flat",
)
button_sett.place(x=804.0, y=7.0, width=50.0, height=50.0)

# midde table
# Create a frame for the middle section
# middle_frame = ttk.Frame(window)
# middle_frame.place(relx=0.5, rely=0.5, anchor="center")

# Define column data
coldata = [
    "LicenseNumber", "CompanyName", "UserCount", "stretch", "email", "password",
    "location"
]

# Dummy data
rowdata = [
    ('A123', 'IzzyCo', 12, 'izzy@example.com', 'password123', 'Location A'),
    ('A136', 'Kimdee Inc.', 45, 'kimdee@example.com', 'kd@123', 'Location B'),
    ('A158', 'Farmadding Co.', 36, 'farm@example.com', 'farm123', 'Location C')
]

# Create a Treeview widget
tree = ttk.Treeview(window, columns=coldata, show="headings")

# Add columns to the Treeview
for col in coldata:
    tree.heading(col, text=col)
    tree.column(col, stretch=True)

# Insert data into the Treeview
for row in rowdata:
    tree.insert("", "end", values=row)

# Pack the Treeview widget
tree.place(x=0, y=65, width=864.0, height=477.0)


# bottom panel
canvas.create_rectangle(0.0, 0.0, 864.0, 64.0, fill="#2A2E31", outline="")

entry_image_1 = PhotoImage(file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(115.0, 573.5, image=entry_image_1)
entry_1 = Entry(bd=0, bg="#D9D9D9", fg="#000716", highlightthickness=0)
entry_1.place(x=10.0, y=551.0, width=210.0, height=43.0)

button_image_play2 = PhotoImage(file=relative_to_assets("icons8-circled-play-64.png"))
button_play2 = Button(
    image=button_image_play2,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("strat queue"),
    relief="flat",
)
button_play2.place(x=230.0, y=548.0, width=50.0, height=50.0)

button_image_pause2 = PhotoImage(file=relative_to_assets("icons8-pause-button-64.png"))
button_pause2 = Button(
    image=button_image_pause2,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("pause queue"),
    relief="flat",
)
button_pause2.place(x=285.0, y=548.0, width=50.0, height=50.0)

button_image_sett2 = PhotoImage(file=relative_to_assets("icons8-slider-64.png"))
button_sett2 = Button(
    image=button_image_sett2,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("open queue settings"),
    relief="flat",
)
button_sett2.place(x=340.0, y=548.0, width=50.0, height=50.0)

window.mainloop()
