# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Button, Canvas, PhotoImage, Tk, ttk

from PIL import Image, ImageTk
from rcmenu import RightClickMenu
from ttkwidgets import DebugWindow, Table
from ttkwidgets.autocomplete import AutocompleteCombobox
from ttkwidgets.frames import Tooltip

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets/frame0")


# print(type(OUTPUT_PATH))
# print(type(ASSETS_PATH
def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("864x605")
window.configure(bg="wheat")
window.title("shusha")
# window.iconbitmap("shusha.ico")
im = Image.open("shusha.ico")
photo = ImageTk.PhotoImage(im)
window.wm_iconphoto(True, photo)
window.resizable(False, False)

canvas = Canvas(
    window,
    bg="gray22",
    height=605,
    width=864,
    bd=0,
    highlightthickness=0,
    relief="ridge",
)
canvas.place(x=0, y=0)

###############################################################################
# top panel
###############################################################################

canvas.create_rectangle(0.0, 541.0, 864.0, 605.0, fill="#2A2E31", outline="")

button_image_add = PhotoImage(file=relative_to_assets("icons8-add-64.png"))
button_add = Button(
    image=button_image_add,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("add downloads"),
    relief="flat",
)
button_add.place(x=10.0, y=7.0, width=50.0, height=50.0)
button_add_ballon = Tooltip(button_add,
                            headertext="Add download",
                            text="Add download")

button_image_play = PhotoImage(
    file=relative_to_assets("icons8-circled-play-64.png"))
button_play = Button(
    image=button_image_play,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("start download"),
    relief="flat",
)
button_play.place(x=65.0, y=7.0, width=50.0, height=50.0)
button_play_ballon = Tooltip(button_play,
                             headertext="Start download",
                             text="Start download")

button_image_pause = PhotoImage(
    file=relative_to_assets("icons8-pause-button-64.png"))
button_pause = Button(
    image=button_image_pause,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("pause download"),
    relief="flat",
)
button_pause.place(x=120.0, y=7.0, width=50.0, height=50.0)
button_pause_ballon = Tooltip(button_pause,
                              headertext="Pause download",
                              text="Pause download")

button_image_up = PhotoImage(file=relative_to_assets("icons8-arrow-64.png"))
button_up = Button(
    image=button_image_up,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Move up"),
    relief="flat",
)
button_up.place(x=175.0, y=7.0, width=50.0, height=50.0)
button_up_ballon = Tooltip(button_up,
                           headertext="Move up",
                           text="Move item up")

button_image_down = PhotoImage(
    file=relative_to_assets("icons8-scroll-down-64.png"))
button_down = Button(
    image=button_image_down,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Move down"),
    relief="flat",
)
button_down.place(x=230.0, y=7.0, width=50.0, height=50.0)
button_down_ballon = Tooltip(button_down,
                             headertext="Move Down",
                             text="Move item down")

button_image_log = PhotoImage(file=relative_to_assets("icons8-log-64.png"))
button_log = Button(
    image=button_image_log,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: DebugWindow(window),
    relief="flat",
)
button_log.place(x=749.0, y=7.0, width=50.0, height=50.0)
button_log_ballon = Tooltip(button_log,
                            headertext="Logs",
                            text="Open log view")

button_image_sett = PhotoImage(
    file=relative_to_assets("icons8-slider_2-64.png"))
button_sett = Button(
    image=button_image_sett,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("open settings"),
    relief="flat",
)
button_sett.place(x=804.0, y=7.0, width=50.0, height=50.0)
button_sett_ballon = Tooltip(button_sett,
                             headertext="Settings",
                             text="Open settings")

###############################################################################
# midde table
###############################################################################

table_columns = [
    "LicenseNumber", "CompanyName", "UserCount", "stretch", "email",
    "password", "location"
]
rowdata = [('A123', 'IzzyCo', 12), ('A136', 'Kimdee Inc.', 45),
           ('A158', 'Farmadding Co.', 36)]

table = Table(window, columns=table_columns, show="headings")

# Add columns to the Table
for col in table_columns:
    table.heading(col, text=col)
    table.column(col, stretch=True)

# Insert data into the Table
for row in rowdata:
    table.insert("", "end", values=row)

table.place(x=0, y=65, width=864.0, height=477.0)

# Create vertical scrollbar
vsb = ttk.Scrollbar(window, orient="vertical", command=table.yview)
vsb.place(x=864.0 - 20, y=65, height=477.0)

# Create horizontal scrollbar
hsb = ttk.Scrollbar(window, orient="horizontal", command=table.xview)
hsb.place(x=0, y=65 + 465.0, width=864.0)

table.configure(yscrollcommand=vsb.set, xscrollcommand=hsb.set)
table.place(x=0, y=65, width=864.0 - 20, height=477.0)


# Example: Creating RightClickMenu for the table
def handle_table_right_click(option, event=None):
    print(f"Table Right Click: {option}")


right_click_options = [
    'Select All', 'Select None', 'Select Completed', 'Select Uncompleted'
]
table_right_click_menu = RightClickMenu(
    table,
    right_click_options,
    callback=lambda option, event=None: handle_table_right_click(
        option, event))

###############################################################################
# bottom panel
###############################################################################

canvas.create_rectangle(0.0, 0.0, 864.0, 64.0, fill="#2A2E31", outline="")

# entry_image_1 = PhotoImage(file=relative_to_assets("entry_1.png"))
# entry_bg_1 = canvas.create_image(115.0, 573.5, image=entry_image_1)
entry_1 = AutocompleteCombobox(window, completevalues=dir(window))
entry_1.config(font=('Arial', 18, "bold"))
entry_1.place(x=10.0, y=551.0, width=210.0, height=43.0)

button_image_play2 = PhotoImage(
    file=relative_to_assets("icons8-circled-play-64.png"))
button_play2 = Button(
    image=button_image_play2,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("strat queue"),
    relief="flat",
)
button_play2.place(x=230.0, y=548.0, width=50.0, height=50.0)
button_play2_ballon = Tooltip(button_play2,
                              headertext="Start Queue",
                              text="Start current queue downloads")

button_image_pause2 = PhotoImage(
    file=relative_to_assets("icons8-pause-button-64.png"))
button_pause2 = Button(
    image=button_image_pause2,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("pause queue"),
    relief="flat",
    text="pause queue",
)
button_pause2.place(x=285.0, y=548.0, width=50.0, height=50.0)
button_pause2_ballon = Tooltip(button_pause2,
                               headertext="Pause Queue",
                               text="Pause the current queue")

button_image_sett2 = PhotoImage(
    file=relative_to_assets("icons8-slider-64.png"))
button_sett2 = Button(
    image=button_image_sett2,
    bg="#2A2E31",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("open queue settings"),
    relief="flat",
)
button_sett2.place(x=340.0, y=548.0, width=50.0, height=50.0)
button_sett2_ballon = Tooltip(button_sett2,
                              headertext="Queue settings",
                              text="Open queue settings")

window.mainloop()
